# Code Review

This notebook covers the datatypes, classes, functions, methods, and other objects found in the PyTorch implementation of ConvTasNet which may exist in TensorFlow by-name, those which may have a differntly named TensorFlow equivalent, and those which need from-scratch implementations with TensorFlow standard, math, distibutions, or the .nn modules.

In [39]:
import tensorflow as tf
import tensorflow_addons as tfa
import pandas as pd

# Data Types

## TensorFlow Tensor

https://www.tensorflow.org/api_docs/python/tf/Tensor

In [3]:
tensor = tf.Tensor

In [4]:
help(tensor)

Help on class Tensor in module tensorflow.python.framework.ops:

class Tensor(tensorflow.python.types.internal.NativeObject, tensorflow.python.types.core.Tensor)
 |  Tensor(op, value_index, dtype)
 |  
 |  A `tf.Tensor` represents a multidimensional array of elements.
 |  
 |  All elements are of a single known data type.
 |  
 |  When writing a TensorFlow program, the main object that is
 |  manipulated and passed around is the `tf.Tensor`.
 |  
 |  A `tf.Tensor` has the following properties:
 |  
 |  * a single data type (float32, int32, or string, for example)
 |  * a shape
 |  
 |  TensorFlow supports eager execution and graph execution.  In eager
 |  execution, operations are evaluated immediately.  In graph
 |  execution, a computational graph is constructed for later
 |  evaluation.
 |  
 |  TensorFlow defaults to eager execution.  In the example below, the
 |  matrix multiplication results are calculated immediately.
 |  
 |  >>> # Compute some values using a Tensor
 |  >>> c =

In [54]:
pd.DataFrame([m for m in dir(tensor) if not m.startswith('_')])

0
0   OVERLOADABLE_OPERATORS
1                consumers
2                   device
3                    dtype
4                     eval
5         experimental_ref
6                get_shape
7                    graph
8                     name
9                       op
10                     ref
11               set_shape
12                   shape
13             value_index

## TensorFlow Module

https://www.tensorflow.org/api_docs/python/tf/Module

In [7]:
module = tf.Module

In [8]:
help(module)

Help on class Module in module tensorflow.python.module.module:

class Module(tensorflow.python.training.tracking.tracking.AutoTrackable)
 |  Module(name=None)
 |  
 |  Base neural network module class.
 |  
 |  A module is a named container for `tf.Variable`s, other `tf.Module`s and
 |  functions which apply to user input. For example a dense layer in a neural
 |  network might be implemented as a `tf.Module`:
 |  
 |  >>> class Dense(tf.Module):
 |  ...   def __init__(self, input_dim, output_size, name=None):
 |  ...     super(Dense, self).__init__(name=name)
 |  ...     self.w = tf.Variable(
 |  ...       tf.random.normal([input_dim, output_size]), name='w')
 |  ...     self.b = tf.Variable(tf.zeros([output_size]), name='b')
 |  ...   def __call__(self, x):
 |  ...     y = tf.matmul(x, self.w) + self.b
 |  ...     return tf.nn.relu(y)
 |  
 |  You can use the Dense layer as you would expect:
 |  
 |  >>> d = Dense(input_dim=3, output_size=2)
 |  >>> d(tf.ones([1, 3]))
 |  <tf.Tensor

In [55]:
pd.DataFrame([m for m in dir(module) if not m.startswith('_')])

0
0                     name
1               name_scope
2  non_trainable_variables
3               submodules
4      trainable_variables
5                variables
6          with_name_scope

## Keras Layer

https://www.tensorflow.org/api_docs/python/tf/keras/layers/Layer

In [10]:
layer = tf.keras.layers.Layer

In [11]:
help(layer)

Help on class Layer in module keras.engine.base_layer:

class Layer(tensorflow.python.module.module.Module, keras.utils.version_utils.LayerVersionSelector)
 |  Layer(trainable=True, name=None, dtype=None, dynamic=False, **kwargs)
 |  
 |  This is the class from which all layers inherit.
 |  
 |  A layer is a callable object that takes as input one or more tensors and
 |  that outputs one or more tensors. It involves *computation*, defined
 |  in the `call()` method, and a *state* (weight variables), defined
 |  either in the constructor `__init__()` or in the `build()` method.
 |  
 |  Users will just instantiate a layer and then treat it as a callable.
 |  
 |  Args:
 |    trainable: Boolean, whether the layer's variables should be trainable.
 |    name: String name of the layer.
 |    dtype: The dtype of the layer's computations and weights. Can also be a
 |      `tf.keras.mixed_precision.Policy`, which allows the computation and weight
 |      dtype to differ. Default of `None` mean

In [46]:
pd.DataFrame(dict(a=[m for m in dir(layer) if not m.startswith('_')][:28],
                  b=[m for m in dir(layer) if not m.startswith('_')][28:]))


a                        b
0       activity_regularizer              get_weights
1                   add_loss            inbound_nodes
2                 add_metric                    input
3                 add_update               input_mask
4               add_variable              input_shape
5                 add_weight               input_spec
6                      apply                   losses
7                      build                  metrics
8                       call                     name
9              compute_dtype               name_scope
10              compute_mask  non_trainable_variables
11      compute_output_shape    non_trainable_weights
12  compute_output_signature           outbound_nodes
13              count_params                   output
14                     dtype              output_mask
15              dtype_policy             output_shape
16                   dynamic              set_weights
17            finalize_state                 stateful
18               from_config               submodules
19                get_config         supports_masking
20              get_input_at                trainable
21         get_input_mask_at      trainable_variables
22        get_input_shape_at        trainable_weights
23            get_losses_for                  updates
24             get_output_at           variable_dtype
25        get_output_mask_at                variables
26       get_output_shape_at                  weights
27           get_updates_for          with_name_scope

## Keras Sequential

Sequential https://www.tensorflow.org/api_docs/python/tf/keras/Sequential

In [13]:
sequential = tf.keras.Sequential

In [14]:
help(sequential)

Help on class Sequential in module keras.engine.sequential:

class Sequential(keras.engine.functional.Functional)
 |  Sequential(layers=None, name=None)
 |  
 |  `Sequential` groups a linear stack of layers into a `tf.keras.Model`.
 |  
 |  `Sequential` provides training and inference features on this model.
 |  
 |  Examples:
 |  
 |  ```python
 |  # Optionally, the first layer can receive an `input_shape` argument:
 |  model = tf.keras.Sequential()
 |  model.add(tf.keras.layers.Dense(8, input_shape=(16,)))
 |  # Afterwards, we do automatic shape inference:
 |  model.add(tf.keras.layers.Dense(4))
 |  
 |  # This is identical to the following:
 |  model = tf.keras.Sequential()
 |  model.add(tf.keras.Input(shape=(16,)))
 |  model.add(tf.keras.layers.Dense(8))
 |  
 |  # Note that you can also omit the `input_shape` argument.
 |  # In that case the model doesn't have any weights until the first call
 |  # to a training/evaluation method (since it isn't yet built):
 |  model = tf.keras.Se

In [53]:
sequential_methods = [m for m in dir(sequential) if not m.startswith('_')] + ['.' for m in range(11)]
pd.DataFrame(
    dict(a=sequential_methods[:25],
         b=sequential_methods[25:50],
         c=sequential_methods[50:75],
         d=sequential_methods[75:])
        )

a                      b                        c  \
0       activity_regularizer            from_config                     name   
1                        add             get_config               name_scope   
2                   add_loss           get_input_at  non_trainable_variables   
3                 add_metric      get_input_mask_at    non_trainable_weights   
4                 add_update     get_input_shape_at           outbound_nodes   
5               add_variable              get_layer                   output   
6                 add_weight         get_losses_for              output_mask   
7                      apply          get_output_at             output_shape   
8                      build     get_output_mask_at                      pop   
9                       call    get_output_shape_at                  predict   
10                   compile        get_updates_for        predict_generator   
11             compute_dtype            get_weights         predict_on_batch   
12              compute_mask          inbound_nodes             predict_step   
13      compute_output_shape                  input            reset_metrics   
14  compute_output_signature             input_mask             reset_states   
15              count_params            input_shape              run_eagerly   
16       distribute_strategy             input_spec                     save   
17                     dtype                 layers                save_spec   
18              dtype_policy           load_weights             save_weights   
19                   dynamic                 losses              set_weights   
20                  evaluate  make_predict_function            state_updates   
21        evaluate_generator     make_test_function                 stateful   
22            finalize_state    make_train_function               submodules   
23                       fit                metrics                  summary   
24             fit_generator          metrics_names         supports_masking   

                      d  
0         test_on_batch  
1             test_step  
2               to_json  
3               to_yaml  
4        train_on_batch  
5            train_step  
6             trainable  
7   trainable_variables  
8     trainable_weights  
9               updates  
10       variable_dtype  
11            variables  
12              weights  
13      with_name_scope  
14                    .  
15                    .  
16                    .  
17                    .  
18                    .  
19                    .  
20                    .  
21                    .  
22                    .  
23                    .  
24                    .

## Keras Model

https://www.tensorflow.org/api_docs/python/tf/keras/Model

In [15]:
model = tf.keras.Model

In [16]:
help(model)

Help on class Model in module keras.engine.training:

class Model(keras.engine.base_layer.Layer, keras.utils.version_utils.ModelVersionSelector)
 |  Model(*args, **kwargs)
 |  
 |  `Model` groups layers into an object with training and inference features.
 |  
 |  Args:
 |      inputs: The input(s) of the model: a `keras.Input` object or list of
 |          `keras.Input` objects.
 |      outputs: The output(s) of the model. See Functional API example below.
 |      name: String, the name of the model.
 |  
 |  There are two ways to instantiate a `Model`:
 |  
 |  1 - With the "Functional API", where you start from `Input`,
 |  you chain layer calls to specify the model's forward pass,
 |  and finally you create your model from inputs and outputs:
 |  
 |  ```python
 |  import tensorflow as tf
 |  
 |  inputs = tf.keras.Input(shape=(3,))
 |  x = tf.keras.layers.Dense(4, activation=tf.nn.relu)(inputs)
 |  outputs = tf.keras.layers.Dense(5, activation=tf.nn.softmax)(x)
 |  model = tf.kera

In [60]:
model_methods = [m for m in dir(model) if not m.startswith('_')] + [
    '.'
    for m in range(100 - len([m for m in dir(model) if not m.startswith('_')]))
]

pd.DataFrame(
    dict(a=model_methods[:25],
         b=model_methods[25:50],
         c=model_methods[50:75],
         d=model_methods[75:]))


a                      b                        c  \
0       activity_regularizer             get_config               name_scope   
1                   add_loss           get_input_at  non_trainable_variables   
2                 add_metric      get_input_mask_at    non_trainable_weights   
3                 add_update     get_input_shape_at           outbound_nodes   
4               add_variable              get_layer                   output   
5                 add_weight         get_losses_for              output_mask   
6                      apply          get_output_at             output_shape   
7                      build     get_output_mask_at                  predict   
8                       call    get_output_shape_at        predict_generator   
9                    compile        get_updates_for         predict_on_batch   
10             compute_dtype            get_weights             predict_step   
11              compute_mask          inbound_nodes            reset_metrics   
12      compute_output_shape                  input             reset_states   
13  compute_output_signature             input_mask              run_eagerly   
14              count_params            input_shape                     save   
15       distribute_strategy             input_spec                save_spec   
16                     dtype                 layers             save_weights   
17              dtype_policy           load_weights              set_weights   
18                   dynamic                 losses            state_updates   
19                  evaluate  make_predict_function                 stateful   
20        evaluate_generator     make_test_function               submodules   
21            finalize_state    make_train_function                  summary   
22                       fit                metrics         supports_masking   
23             fit_generator          metrics_names            test_on_batch   
24               from_config                   name                test_step   

                      d  
0               to_json  
1               to_yaml  
2        train_on_batch  
3            train_step  
4             trainable  
5   trainable_variables  
6     trainable_weights  
7               updates  
8        variable_dtype  
9             variables  
10              weights  
11      with_name_scope  
12                    .  
13                    .  
14                    .  
15                    .  
16                    .  
17                    .  
18                    .  
19                    .  
20                    .  
21                    .  
22                    .  
23                    .  
24                    .

# Activations

## PReLU

PreLu https://www.tensorflow.org/api_docs/python/tf/keras/layers/PReLU

In [17]:
prelu = tf.keras.layers.PReLU

In [18]:
help(prelu)

Help on class PReLU in module keras.layers.advanced_activations:

class PReLU(keras.engine.base_layer.Layer)
 |  PReLU(alpha_initializer='zeros', alpha_regularizer=None, alpha_constraint=None, shared_axes=None, **kwargs)
 |  
 |  Parametric Rectified Linear Unit.
 |  
 |  It follows:
 |  
 |  ```
 |    f(x) = alpha * x for x < 0
 |    f(x) = x for x >= 0
 |  ```
 |  
 |  where `alpha` is a learned array with the same shape as x.
 |  
 |  Input shape:
 |    Arbitrary. Use the keyword argument `input_shape`
 |    (tuple of integers, does not include the samples axis)
 |    when using this layer as the first layer in a model.
 |  
 |  Output shape:
 |    Same shape as the input.
 |  
 |  Args:
 |    alpha_initializer: Initializer function for the weights.
 |    alpha_regularizer: Regularizer for the weights.
 |    alpha_constraint: Constraint for the weights.
 |    shared_axes: The axes along which to share learnable
 |      parameters for the activation function.
 |      For example, if 

In [62]:
prelu_methods = [m for m in dir(prelu) if not m.startswith('_')] + [
    '.'
    for m in range(100 - len([m for m in dir(prelu) if not m.startswith('_')]))
]

pd.DataFrame(
    dict(a=prelu_methods[:25],
         b=prelu_methods[25:50],
         c=prelu_methods[50:75]))

a                        b                  c
0       activity_regularizer       get_output_mask_at  trainable_weights
1                   add_loss      get_output_shape_at            updates
2                 add_metric          get_updates_for     variable_dtype
3                 add_update              get_weights          variables
4               add_variable            inbound_nodes            weights
5                 add_weight                    input    with_name_scope
6                      apply               input_mask                  .
7                      build              input_shape                  .
8                       call               input_spec                  .
9              compute_dtype                   losses                  .
10              compute_mask                  metrics                  .
11      compute_output_shape                     name                  .
12  compute_output_signature               name_scope                  .
13              count_params  non_trainable_variables                  .
14                     dtype    non_trainable_weights                  .
15              dtype_policy           outbound_nodes                  .
16                   dynamic                   output                  .
17            finalize_state              output_mask                  .
18               from_config             output_shape                  .
19                get_config              set_weights                  .
20              get_input_at                 stateful                  .
21         get_input_mask_at               submodules                  .
22        get_input_shape_at         supports_masking                  .
23            get_losses_for                trainable                  .
24             get_output_at      trainable_variables                  .

## ReLU

ReLU https://www.tensorflow.org/api_docs/python/tf/keras/layers/ReLU

In [19]:
relu = tf.nn.relu

In [20]:
help(relu)

Help on function relu in module tensorflow.python.ops.gen_nn_ops:

relu(features, name=None)
    Computes rectified linear: `max(features, 0)`.
    
    See: https://en.wikipedia.org/wiki/Rectifier_(neural_networks)
    Example usage:
    >>> tf.nn.relu([-2., 0., 3.]).numpy()
    array([0., 0., 3.], dtype=float32)
    
    Args:
      features: A `Tensor`. Must be one of the following types: `float32`, `float64`, `int32`, `uint8`, `int16`, `int8`, `int64`, `bfloat16`, `uint16`, `half`, `uint32`, `uint64`, `qint8`.
      name: A name for the operation (optional).
    
    Returns:
      A `Tensor`. Has the same type as `features`.



In [65]:
[m for m in dir(relu) if not m.startswith('_')]

[]

## Sigmoid

https://www.tensorflow.org/api_docs/python/tf/keras/activations/sigmoid

In [21]:
sigmoid = tf.nn.sigmoid

In [22]:
help(sigmoid)

Help on function sigmoid in module tensorflow.python.ops.math_ops:

sigmoid(x, name=None)
    Computes sigmoid of `x` element-wise.
    
    Formula for calculating $\mathrm{sigmoid}(x) = y = 1 / (1 + \exp(-x))$.
    
    For $x \in (-\infty, \infty)$, $\mathrm{sigmoid}(x) \in (0, 1)$.
    
    Example Usage:
    
    If a positive number is large, then its sigmoid will approach to 1 since the
    formula will be `y = <large_num> / (1 + <large_num>)`
    
    >>> x = tf.constant([0.0, 1.0, 50.0, 100.0])
    >>> tf.math.sigmoid(x)
    <tf.Tensor: shape=(4,), dtype=float32,
    numpy=array([0.5      , 0.7310586, 1.       , 1.       ], dtype=float32)>
    
    If a negative number is large, its sigmoid will approach to 0 since the
    formula will be `y = 1 / (1 + <large_num>)`
    
    >>> x = tf.constant([-100.0, -50.0, -1.0, 0.0])
    >>> tf.math.sigmoid(x)
    <tf.Tensor: shape=(4,), dtype=float32, numpy=
    array([0.0000000e+00, 1.9287499e-22, 2.6894143e-01, 0.5],
          dtype=fl

In [66]:
[m for m in dir(sigmoid) if not m.startswith('_')]

[]

# Other

## Group Normalization

https://www.tensorflow.org/addons/api_docs/python/tfa/layers/GroupNormalization

In [23]:
group_norm = tfa.layers.GroupNormalization

In [24]:
help(group_norm)

Help on class GroupNormalization in module tensorflow_addons.layers.normalizations:

class GroupNormalization(keras.engine.base_layer.Layer)
 |  GroupNormalization(groups: int = 32, axis: int = -1, epsilon: float = 0.001, center: bool = True, scale: bool = True, beta_initializer: Union[NoneType, dict, str, Callable, keras.initializers.initializers_v2.Initializer] = 'zeros', gamma_initializer: Union[NoneType, dict, str, Callable, keras.initializers.initializers_v2.Initializer] = 'ones', beta_regularizer: Union[NoneType, dict, str, Callable, keras.regularizers.Regularizer] = None, gamma_regularizer: Union[NoneType, dict, str, Callable, keras.regularizers.Regularizer] = None, beta_constraint: Union[NoneType, dict, str, Callable, keras.constraints.Constraint] = None, gamma_constraint: Union[NoneType, dict, str, Callable, keras.constraints.Constraint] = None, **kwargs)
 |  
 |  Group normalization layer.
 |  
 |  Source: "Group Normalization" (Yuxin Wu & Kaiming He, 2018)
 |  https://arxiv.

In [69]:
gn_methods = [m for m in dir(group_norm) if not m.startswith('_')] + [
    '.'
    for m in range(100 - len([m for m in dir(group_norm) if not m.startswith('_')]))
]

pd.DataFrame(dict(a=gn_methods[:25], b=gn_methods[25:50], c=gn_methods[50:75]))


a                        b                  c
0       activity_regularizer       get_output_mask_at  trainable_weights
1                   add_loss      get_output_shape_at            updates
2                 add_metric          get_updates_for     variable_dtype
3                 add_update              get_weights          variables
4               add_variable            inbound_nodes            weights
5                 add_weight                    input    with_name_scope
6                      apply               input_mask                  .
7                      build              input_shape                  .
8                       call               input_spec                  .
9              compute_dtype                   losses                  .
10              compute_mask                  metrics                  .
11      compute_output_shape                     name                  .
12  compute_output_signature               name_scope                  .
13              count_params  non_trainable_variables                  .
14                     dtype    non_trainable_weights                  .
15              dtype_policy           outbound_nodes                  .
16                   dynamic                   output                  .
17            finalize_state              output_mask                  .
18               from_config             output_shape                  .
19                get_config              set_weights                  .
20              get_input_at                 stateful                  .
21         get_input_mask_at               submodules                  .
22        get_input_shape_at         supports_masking                  .
23            get_losses_for                trainable                  .
24             get_output_at      trainable_variables                  .

## Keras Conv1D

https://www.tensorflow.org/api_docs/python/tf/keras/layers/Conv1D

In [25]:
conv1d = tf.keras.layers.Conv1D

In [26]:
help(conv1d)

Help on class Conv1D in module keras.layers.convolutional:

class Conv1D(Conv)
 |  Conv1D(filters, kernel_size, strides=1, padding='valid', data_format='channels_last', dilation_rate=1, groups=1, activation=None, use_bias=True, kernel_initializer='glorot_uniform', bias_initializer='zeros', kernel_regularizer=None, bias_regularizer=None, activity_regularizer=None, kernel_constraint=None, bias_constraint=None, **kwargs)
 |  
 |  1D convolution layer (e.g. temporal convolution).
 |  
 |  This layer creates a convolution kernel that is convolved
 |  with the layer input over a single spatial (or temporal) dimension
 |  to produce a tensor of outputs.
 |  If `use_bias` is True, a bias vector is created and added to the outputs.
 |  Finally, if `activation` is not `None`,
 |  it is applied to the outputs as well.
 |  
 |  When using this layer as the first layer in a model,
 |  provide an `input_shape` argument
 |  (tuple of integers or `None`, e.g.
 |  `(10, 128)` for sequences of 10 vector

In [71]:
conv1d_methods = [m for m in dir(conv1d) if not m.startswith('_')] + [
    '.'
    for m in range(100 - len([m
                              for m in dir(conv1d) if not m.startswith('_')]))
]

pd.DataFrame(
    dict(a=conv1d_methods[:25],
         b=conv1d_methods[25:50],
         c=conv1d_methods[50:75]))

a                        b                    c
0       activity_regularizer            get_output_at  trainable_variables
1                   add_loss       get_output_mask_at    trainable_weights
2                 add_metric      get_output_shape_at              updates
3                 add_update          get_updates_for       variable_dtype
4               add_variable              get_weights            variables
5                 add_weight            inbound_nodes              weights
6                      apply                    input      with_name_scope
7                      build               input_mask                    .
8                       call              input_shape                    .
9              compute_dtype               input_spec                    .
10              compute_mask                   losses                    .
11      compute_output_shape                  metrics                    .
12  compute_output_signature                     name                    .
13            convolution_op               name_scope                    .
14              count_params  non_trainable_variables                    .
15                     dtype    non_trainable_weights                    .
16              dtype_policy           outbound_nodes                    .
17                   dynamic                   output                    .
18            finalize_state              output_mask                    .
19               from_config             output_shape                    .
20                get_config              set_weights                    .
21              get_input_at                 stateful                    .
22         get_input_mask_at               submodules                    .
23        get_input_shape_at         supports_masking                    .
24            get_losses_for                trainable                    .

# Custom

## ModuleList

In [ ]:
class ModuleList(tf.Module):

    def __init__(self, submodules=None):
        super(ModuleList, self).__init__()

        if submodules is not None:
            self._submodules = submodules            
        else:
            self._submodules = []

    def set_submodules(self):
        self._submodules = tuple(self._submodules)

In [ ]:
ms = []
for m in range(5):
    ms.append(tf.Module())

In [ ]:
zed = ModuleList(ms)

In [ ]:
zed.submodules

(<tensorflow.python.module.module.Module at 0x7f82de38ea60>,
 <tensorflow.python.module.module.Module at 0x7f82de38e8b0>)

# Needs Verification

## TensorFlow.reshape -> PyTorch.Tensor.view

In [27]:
help(tf.reshape)

Help on function reshape in module tensorflow.python.ops.array_ops:

reshape(tensor, shape, name=None)
    Reshapes a tensor.
    
    Given `tensor`, this operation returns a new `tf.Tensor` that has the same
    values as `tensor` in the same order, except with a new shape given by
    `shape`.
    
    >>> t1 = [[1, 2, 3],
    ...       [4, 5, 6]]
    >>> print(tf.shape(t1).numpy())
    [2 3]
    >>> t2 = tf.reshape(t1, [6])
    >>> t2
    <tf.Tensor: shape=(6,), dtype=int32,
      numpy=array([1, 2, 3, 4, 5, 6], dtype=int32)>
    >>> tf.reshape(t2, [3, 2])
    <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
      array([[1, 2],
             [3, 4],
             [5, 6]], dtype=int32)>
    
    The `tf.reshape` does not change the order of or the total number of elements
    in the tensor, and so it can reuse the underlying data buffer. This makes it
    a fast operation independent of how big of a tensor it is operating on.
    
    >>> tf.reshape([1, 2, 3], [2, 2])
    Traceback (mos